routes/web.php
<?php
Route::get('/', function(){
    if(Auth::check() && Auth::user()->role =='admin'){
		
		 return redirect('/admin');
        
    }else if(Auth::check() && Auth::user()->role =='user'){
        return redirect('/'); 
    }else{
		return view('/');
	} 
	 
});

Auth::routes();


 
	Route::get('/', 'HomeController@indexHome');
	Route::get('/changepassword','ChangepasswordController@changepasswords');
    Route::post('/changepassword','ChangepasswordController@changepassword');
 


Route::group(['middleware' => ['user']], function () {
	
	
});



Route::group(['middleware' => ['cors']], function () {
Route::get('addcategory', 'CategoryAjaxController@AddCategory');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about','ContactController@about');
Route::get('/contact','ContactController@index');
Route::post('/contact','ContactController@create');
Route::get('/get_products','UserProductsController@product');
<<<<<<< HEAD
Route::get('/product_detail/{id}','UserProductsController@product_detail');

//Route::resource('/wishlist', 'WishlistController', ['except' => ['create', 'edit', 'show', 'update']]);
=======
<<<<<<< HEAD
Route::get('/product_detail/{id}','UserProductsController@product_detail');
=======
>>>>>>> 291d32694acc75f361be1752c882fa5852916acd
>>>>>>> 9cc800d408ce84b53db52b272c6a37bac30be335


Route::resource('ajaxcategory','CategoryAjaxController');
Route::get('/home', 'HomeController@index')->name('home');

/*Cart routes*/
Route::post('/cart','CartController@add');
Route::get('/cartproducts','CartController@GetCartProducts');
Route::post('/remove','CartController@removeItem');
Route::post('/update','CartController@updateItem');
/*Cart routes end*/
<<<<<<< HEAD


Route::get('/wishlist','WishlistController@view');
Route::post('/wishlists','WishlistController@store');
 Route::get('/wishlistproducts','WishlistController@index');
 Route::get('/delete/{id}','WishlistController@destroy');
// Route::post('/update','WishlistController@updateItem');


=======
>>>>>>> 9cc800d408ce84b53db52b272c6a37bac30be335
Route::group(['middleware' => ['admin']], function () {
	
Route::get('/admin', function () {
    return view('backend/index');
});	
Route::get('admin/product_index', 'AdminProductController@index');
Route::post('admin/product_store', 'AdminProductController@store');
Route::get('admin/product_delete/{id}', 'AdminProductController@destroy');
Route::get('admin/product_edit/{id}', 'AdminProductController@edit');

Route::resource('/ajaxcategory','CategoryAjaxController');

Route::get('admin/uploadimage_index', 'UploadImageController@index');
Route::post('admin/uploadimage_store', 'UploadImageController@store');
Route::get('admin/uploadimage_delete/{id}', 'UploadImageController@destroy');
Route::get('admin/uploadimage_edit/{id}', 'UploadImageController@edit');

Route::post('/update_Coupan','CoupanAjaxController@Editcoupan');
Route::post('/create_Coupan','CoupanAjaxController@Addcoupan');
Route::resource('ajaxcoupan','CoupanAjaxController');

Route::get('admin/customer_index', 'CustomerController@index');
Route::post('admin/customer_store', 'CustomerController@store');
Route::get('admin/customer_delete/{id}', 'CustomerController@destroy');
Route::get('admin/customer_edit/{id}', 'CustomerController@edit');

Route::resource('/ajaxcategory','CategoryAjaxController');
Route::post('/update_Cat','CategoryAjaxController@EditCat');
Route::post('/create_Cat','CategoryAjaxController@AddCategory');
});

resources/views/backend/layouts/main.blade.php
<html>
<head>
<title>Craftfort</title>
<meta charset="utf-8"> 
 
	<meta charset="utf-8">
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Nobile:400,500,700|Philosopher:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="/public/css/admin.css">
	<link rel="stylesheet" href="/public/css/mystyle.css">
	<link rel="icon" href="favicon.ico" type="image/icon" sizes="16x16">
	<link  href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">

</head>
<body>



@include('backend.include.header')
@include('backend.include.sidebar')

@yield('content')


@include('backend.include.footer')
	<script src="/public/js/vendors.bundle.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	<script src="/public/js/scripts.bundle.js"></script>

    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
		
<script>
		 $(function() {
	 
	 $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
    var table = $('#table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('ajaxcategory.index') }}",
        columns: [
           {data: 'DT_RowIndex', name: 'DT_RowIndex'},
			{ data: 'cat_name', name: 'cat_name' },
			{ data: 'cat_details', name: 'cat_details' },
			{data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
     $('#createNewcat').click(function () {
		 
        //$('#saveBtn').val("create-product");
        //$('#cat_id').val('');
        //$('#categoryForm').trigger("reset");
        //$('#modelHeading').html("Create New Product");
        $('#ajaxModel_cat').modal('show');
    });
	$('body').on('click', '.deleteProduct', function () {
     
        var cat_id = $(this).data("id");
        confirm("Are You sure want to delete !");
      
        $.ajax({
            type: "DELETE",
            url: "{{ route('ajaxcategory.store') }}"+'/'+cat_id,
            success: function (data) {
				window.location.reload();
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });
	
	/* $('body').on('click', '.editProduct', function () {

      var cat_id = $(this).data('id');
	  alert(cat_id);
		  $.get("{{ route('ajaxcategory.index') }}" +'/' + cat_id +'/edit', function (data) {
          $('#modelHeading').html("Edit category");
          $('#saveBtn').val("edit-user");
          $('#ajaxModel').modal('show');
          $('#cat_id').val(data.id);
          $('#cat_name').val(data.cat_name);
          $('#cat_details').val(data.cat_details);
		  
      }) 
   }); */
	/* $('#saveBtn').click(function (e) {
        e.preventDefault();
        $(this).html('Sending..');
    
        $.ajax({
          data: $('#categoryForm').serialize(),
          url: "{{ route('ajaxcategory.store') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {
     
              $('#categoryForm').trigger("reset");
              $('#ajaxModel').modal('hide');
              table.draw();
         
          },
          error: function (data) {
              console.log('Error:', data);
              $('#saveBtn').html('Save Changes');
          }
      });
    }); */
	
	
	
	
   
var table = $('#table_coupan').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('ajaxcoupan.index') }}",
        columns: [
           {data: 'DT_RowIndex', name: 'DT_RowIndex'},
			{ data: 'coupon_name', name: 'coupon_name' },
			{ data: 'discount', name: 'discount' },
			{data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
     $('#createNewcoupan').click(function () {
		 
        $('#ajaxModelcreate_coupan').modal('show');
    });
	$('body').on('click', '.deleteCoupan', function () {
     
        var coupan_id = $(this).data("id");
        confirm("Are You sure want to delete !");
      
        $.ajax({
            type: "DELETE",
            url: "{{ route('ajaxcoupan.store') }}"+'/'+coupan_id,
            success: function (data) {
				window.location.reload();
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });
	
	
   });
window.onload = function() {
 
 
var chart = new CanvasJS.Chart("chartContainer", {
	theme: "light2",
	title: {
		text: "NVIDIA Corporation Stock Price - 2017"
	},
	axisX: {
		valueFormatString: "MMM",
		intervalType: "month",
		interval: 1
	},
	axisY: {
		title: "Stock Price (in USD)",
		includeZero: false,
		prefix: "$"
	},
	data: [{
		type: "ohlc",
		xValueType: "dateTime",
		yValueFormatString: "$#,##0.0",
		xValueFormatString: "MMM"
	}]
});
chart.render();
 }
 
 function openCat(id,name,details){
	 $("#cat_id").val(id);
	  $("#cat_name").val(name); 
	  $("#cat_detail").val(details);
	 $("#ajaxModel").modal('show');
 }
 function openCoupan(id,coupon_name,discount){
	 $("#coupan_id").val(id);
	  $("#coupon_name").val(coupon_name); 
	  $("#discount").val(discount); 
	 $("#ajaxModeledit_coupan").modal('show');
 }

</script>


</body>

</html>

resources/views/backend/layouts/main1.blade.php
<html>
<head>
<title>Craftfort</title>
<meta charset="utf-8"> 
 
	<meta charset="utf-8">
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Nobile:400,500,700|Philosopher:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="/public/css/admin.css">
	<link rel="stylesheet" href="/public/css/mystyle.css">
	<link rel="icon" href="favicon.ico" type="image/icon" sizes="16x16">
	<link  href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">

</head>
<body>



@include('backend.include.header')
@include('backend.include.sidebar')
@include('backend.include.modal')
@yield('content')


@include('backend.include.footer')

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
		<script src="/public/js/data.js"></script>
<script>
		 $(function() {
	 
	 $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
    var table = $('#table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('ajaxcategory.index') }}",
        columns: [
           {data: 'DT_RowIndex', name: 'DT_RowIndex'},
			{ data: 'cat_name', name: 'cat_name' },
			{ data: 'cat_details', name: 'cat_details' },
			{data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
     $('#createNewcat').click(function () {
		 
        //$('#saveBtn').val("create-product");
        //$('#cat_id').val('');
        //$('#categoryForm').trigger("reset");
        //$('#modelHeading').html("Create New Product");
        $('#ajaxModel_cat').modal('show');
    });
	$('body').on('click', '.deleteProduct', function () {
     
        var cat_id = $(this).data("id");
        confirm("Are You sure want to delete !");
      
        $.ajax({
            type: "DELETE",
            url: "{{ route('ajaxcategory.store') }}"+'/'+cat_id,
            success: function (data) {
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });
	
	/* $('body').on('click', '.editProduct', function () {

      var cat_id = $(this).data('id');
	  alert(cat_id);
		  $.get("{{ route('ajaxcategory.index') }}" +'/' + cat_id +'/edit', function (data) {
          $('#modelHeading').html("Edit category");
          $('#saveBtn').val("edit-user");
          $('#ajaxModel').modal('show');
          $('#cat_id').val(data.id);
          $('#cat_name').val(data.cat_name);
          $('#cat_details').val(data.cat_details);
		  
      }) 
   }); */
	/* $('#saveBtn').click(function (e) {
        e.preventDefault();
        $(this).html('Sending..');
    
        $.ajax({
          data: $('#categoryForm').serialize(),
          url: "{{ route('ajaxcategory.store') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {
     
              $('#categoryForm').trigger("reset");
              $('#ajaxModel').modal('hide');
              table.draw();
         
          },
          error: function (data) {
              console.log('Error:', data);
              $('#saveBtn').html('Save Changes');
          }
      });
    }); */
	
	
	
	
   });
window.onload = function() {
 
 
var chart = new CanvasJS.Chart("chartContainer", {
	theme: "light2",
	title: {
		text: "NVIDIA Corporation Stock Price - 2017"
	},
	axisX: {
		valueFormatString: "MMM",
		intervalType: "month",
		interval: 1
	},
	axisY: {
		title: "Stock Price (in USD)",
		includeZero: false,
		prefix: "$"
	},
	data: [{
		type: "ohlc",
		xValueType: "dateTime",
		yValueFormatString: "$#,##0.0",
		xValueFormatString: "MMM"
	}]
});
chart.render();
 }
 
 function openCat(id,name,details){
	 $("#cat_id").val(id);
	  $("#cat_name").val(name); 
	  $("#cat_detail").val(details);
	 $("#ajaxModel").modal('show');
 }
</script>


</body>

</html>